server:
  port: 8068
spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: ${POSTGRESQL_URL:jdbc:postgresql://localhost:5432/trade_bot}
    username: ${POSTGRESQL_USER:postgres}
    password: ${POSTGRESQL_PASSWORD:123}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: false
    hibernate:
      ddl-auto: none
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
open:
  api:
    serverName: api-service dev
    server: https://localhost:${server.port}
    title: ${API_TITLE:DUMMY-API-TITLE}
    version: 1.0.0
    description: API for backend description dev

